// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tw.idv.ken.mymovies.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import tw.idv.ken.mymovies.model.Studio;
import tw.idv.ken.mymovies.model.StudioDataOnDemand;
import tw.idv.ken.mymovies.model.StudioIntegrationTest;

privileged aspect StudioIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StudioIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StudioIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: StudioIntegrationTest: @Transactional;
    
    @Autowired
    StudioDataOnDemand StudioIntegrationTest.dod;
    
    @Test
    public void StudioIntegrationTest.testCountStudios() {
        Assert.assertNotNull("Data on demand for 'Studio' failed to initialize correctly", dod.getRandomStudio());
        long count = Studio.countStudios();
        Assert.assertTrue("Counter for 'Studio' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StudioIntegrationTest.testFindStudio() {
        Studio obj = dod.getRandomStudio();
        Assert.assertNotNull("Data on demand for 'Studio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Studio' failed to provide an identifier", id);
        obj = Studio.findStudio(id);
        Assert.assertNotNull("Find method for 'Studio' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Studio' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StudioIntegrationTest.testFindAllStudios() {
        Assert.assertNotNull("Data on demand for 'Studio' failed to initialize correctly", dod.getRandomStudio());
        long count = Studio.countStudios();
        Assert.assertTrue("Too expensive to perform a find all test for 'Studio', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Studio> result = Studio.findAllStudios();
        Assert.assertNotNull("Find all method for 'Studio' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Studio' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StudioIntegrationTest.testFindStudioEntries() {
        Assert.assertNotNull("Data on demand for 'Studio' failed to initialize correctly", dod.getRandomStudio());
        long count = Studio.countStudios();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Studio> result = Studio.findStudioEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Studio' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Studio' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StudioIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Studio' failed to initialize correctly", dod.getRandomStudio());
        Studio obj = dod.getNewTransientStudio(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Studio' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Studio' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Studio' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StudioIntegrationTest.testRemove() {
        Studio obj = dod.getRandomStudio();
        Assert.assertNotNull("Data on demand for 'Studio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Studio' failed to provide an identifier", id);
        obj = Studio.findStudio(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Studio' with identifier '" + id + "'", Studio.findStudio(id));
    }
    
}
