// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tw.idv.ken.mymovies.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import tw.idv.ken.mymovies.model.Studio;
import tw.idv.ken.mymovies.model.StudioDataOnDemand;

privileged aspect StudioDataOnDemand_Roo_DataOnDemand {
    
    declare @type: StudioDataOnDemand: @Component;
    
    private Random StudioDataOnDemand.rnd = new SecureRandom();
    
    private List<Studio> StudioDataOnDemand.data;
    
    public Studio StudioDataOnDemand.getNewTransientStudio(int index) {
        Studio obj = new Studio();
        setFilmCount(obj, index);
        setName(obj, index);
        setUrl(obj, index);
        return obj;
    }
    
    public void StudioDataOnDemand.setFilmCount(Studio obj, int index) {
        Integer filmCount = new Integer(index);
        obj.setFilmCount(filmCount);
    }
    
    public void StudioDataOnDemand.setName(Studio obj, int index) {
        String name = "name_" + index;
        if (name.length() > 255) {
            name = name.substring(0, 255);
        }
        obj.setName(name);
    }
    
    public void StudioDataOnDemand.setUrl(Studio obj, int index) {
        String url = "urlxxxxx_" + index;
        if (url.length() > 255) {
            url = url.substring(0, 255);
        }
        obj.setUrl(url);
    }
    
    public Studio StudioDataOnDemand.getSpecificStudio(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Studio obj = data.get(index);
        Long id = obj.getId();
        return Studio.findStudio(id);
    }
    
    public Studio StudioDataOnDemand.getRandomStudio() {
        init();
        Studio obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Studio.findStudio(id);
    }
    
    public boolean StudioDataOnDemand.modifyStudio(Studio obj) {
        return false;
    }
    
    public void StudioDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Studio.findStudioEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Studio' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Studio>();
        for (int i = 0; i < 10; i++) {
            Studio obj = getNewTransientStudio(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
