// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tw.idv.ken.mymovies.model;

import org.springframework.beans.factory.annotation.Configurable;
import tw.idv.ken.mymovies.model.Studio;

privileged aspect Studio_Roo_Configurable {
    
    declare @type: Studio: @Configurable;
    
}
